version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "./bridge:/usr/src/app/bridge"
    restart: 'no'
    command: gunicorn bridge.asgi:app -w 1 -k uvicorn.workers.UvicornWorker
    networks:
      - bridge-net


  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: "no"
    networks:
      - bridge-net

  rabbitmq:
    image: rabbitmq:3.7.5-management
    restart: "no"
    env_file: .env
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
      - 15672:15672
      - 5671:5671
      - 15671:15671
      - 25672:25672
      - 4369:4369
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
      - ./rabbitmq-init.sh:/rabbitmq-init.sh
    networks:
      - bridge-net


volumes:
  db-data:
  rabbitmq-data:
  postgres-data:

networks:
  bridge-net: